server:
  port: 8081

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

logging:
  level:
    root: info
    org.apache.http.wire: info
    org.apache.http.headers: info
    org.mybatis: debug
    java.sql: debug
    #    org.springframework.web: trace
    org.springframework.web: info
    com:
      roncoo:
        eshop:
          cache:
            ha: info